### ISSUE TITLE
Behavior inconsistent between Python <3.10 and >=3.10

### ISSUE THREAD

**Issue by steverice** [asottile/classify-imports#155]
### `unclassifiable_application_modules`

Under Python 3.10+, the [system builtins are checked for the import](https://github.com/asottile/classify-imports/blob/8d0e115b4b95dbe6bcfafbaae2d1323ba7fbdfbf/classify_imports.py#L105-L111) before anything else.

Under Python <3.10, [`unclassifiable_application_modules` is checked](https://github.com/asottile/classify-imports/blob/8d0e115b4b95dbe6bcfafbaae2d1323ba7fbdfbf/classify_imports.py#L173-L176) before anything else.

As a result, if a builtin module is specified in `unclassifiable_application_modules`, it will be reported as an application module under Python <3.10 and a builtin under Python 3.10+.

I'm not sure what the "correct" behavior for these are, but it does seem that both should be consistent among Python versions.

### `application_directories`

Furthermore, the difference in `find_stdlib` under Python <3.10 is different from the `base in sys.stdlib_module_names` check under 3.10+. If the former is configured with an empty set of `application_directories`, it will identify an arbitrary module in the current directory as a builtin, while `sys.stdlib_module_names` does not. Here the behavior seems more clearly correct under Python 3.10+.

**Comment by asottile** [comment]
neither of those should matter -- classifying a stdlib module as an application module is always wrong -- garbage in garbage out
